name: Prettier
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  NODE_VERSION: 18
jobs:
  setup:
    steps: 
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
  typescript:
    name: TypeScript
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run Prettier
        run: npm run build
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run ESLint
        run: npm run eslint-ci
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run Prettier
        run: npm run prettier-ci