name: Prettier
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  NODE_VERSION: 18
jobs:
  everything:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: TypeScript
        run: npm run build
      - name: ESLint
        run: npm run eslint-ci
      - name: Prettier
        run: npm run prettier-ci