name: ESLint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  checks: read
  contents: read

jobs:
  run-linters:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          prettier: true